name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: '6.3'
      - name: Show Swift version
        run: swift --version
      - name: Run Swift tests
        run: swift test